In [6]:
import pandas as pd

df = pd.read_csv('cleaned train_identity.csv')
df = df.drop('Unnamed: 0', axis = 1)

In [38]:
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn import preprocessing
from patsy import dmatrices


#formula = 'isFraud ~ id_01 + id_02 + id_05 + id_05 + id_11 + C{id_12} + C{id_13} + C{id_15}+\
#            C{id_16} + C{id_17} + C{id_19} + C{id_20} + C{id_28} + C{id_29} + C{id_31} + C{id_35}\
#            + C{id_36} + C{id_37} + C{id_38}

X = df.drop(['isFraud', 'TransactionID'], axis=1)
y = df['isFraud']

#X, y = dmatrices( )

model = RandomForestClassifier(n_estimators = 100, max_depth = 10, random_state = 0)
#model.fit(X,y)

X
cat_list = list()
le = preprocessing.LabelEncoder()
#for variable in cat_list:
#    le.fit(df['{}'.format(variable)])
#    df['{}'.format(variable)] = le.transform()
#le.fit(['chrome','chrome','safari','firefox'])
#le.transform

df['id_15'] = le.fit_transform(df['id_15'])
df['id_16'] = le.fit_transform(df['id_16'])
df['id_12'] = le.fit_transform(df['id_12'])
df['id_13'] = le.fit_transform(df['id_13'])
df['id_17'] = le.fit_transform(df['id_17'])
df['id_19'] = le.fit_transform(df['id_19'])
df['id_20'] = le.fit_transform(df['id_20'])
df['id_28'] = le.fit_transform(df['id_28'])
df['id_29'] = le.fit_transform(df['id_29'])
df['id_31'] = le.fit_transform(df['id_31'])
df['id_35'] = le.fit_transform(df['id_35'])
df['id_36'] = le.fit_transform(df['id_36'])
df['id_37'] = le.fit_transform(df['id_37'])
df['id_38'] = le.fit_transform(df['id_38'])
df['DeviceType'] = le.fit_transform(df['DeviceType'])
df['DeviceInfo'] = le.fit_transform(df['DeviceInfo'])
df.head()

,TransactionID,id_01,id_02,id_05,id_06,id_11,id_12,id_13,id_15,id_16,...,id_28,id_29,id_31,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,isFraud
0,3538718,-5.0,308818.0,2.0,-5.0,100.000000,0,25,0,0,...,0,0,78,0,0,1,1,0,712,0
1,3566934,-5.0,12600.0,9.0,-100.0,100.000000,1,9,1,1,...,1,1,82,1,0,0,1,1,705,0
2,2989292,-5.0,438030.0,0.0,0.0,100.000000,1,24,1,1,...,1,1,97,1,0,0,0,0,268,0
3,3100078,-5.0,42971.0,0.0,0.0,100.000000,1,24,1,1,...,1,1,82,1,0,0,1,1,705,0
4,3102318,-5.0,141536.0,0.0,0.0,90.199997,1,25,1,1,...,0,0,40,1,0,1,0,0,647,0